name: Build-Qt6-Everywhere-IMX6ULL

on: 
  workflow_dispatch:

jobs:
  build-qt6:
    runs-on: ubuntu-latest
    timeout-minutes: 360 

    steps:
      - name: Maximize Build Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean

      - name: Install Host Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build build-essential python3 perl \
            libgl1-mesa-dev libx11-dev libxkbcommon-dev libfontconfig1-dev \
            libdbus-1-dev libudev-dev libgles2-mesa-dev # 编译 GUI 必须的宿主库

      - name: Setup Arm Toolchain
        run: |
          mkdir -p /opt/gcc-arm-11.2
          curl -L "https://developer.arm.com/-/media/files/downloads/gnu/11.2-2022.02/binrel/gcc-arm-11.2-2022.02-x86_64-arm-none-linux-gnueabihf.tar.xz" | tar -xJ --strip-components=1 -C /opt/gcc-arm-11.2
          echo "/opt/gcc-arm-11.2/bin" >> $GITHUB_PATH

      - name: Download Qt 6.5 Source
        run: |
          curl -L "https://download.qt.io/official_releases/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz" -o qt6.tar.xz
          mkdir qt6-src && tar -xJf qt6.tar.xz -C qt6-src --strip-components=1

      - name: Configure Qt 6
        run: |
          mkdir qt6-build && cd qt6-build
          ../qt-src/configure \
            -release \
            -device linux-imx6-g++ \
            -device-option CROSS_COMPILE=/opt/gcc-arm-11.2/bin/arm-none-linux-gnueabihf- \
            -sysroot /opt/gcc-arm-11.2/arm-none-linux-gnueabihf/libc \
            -prefix /usr/local/qt6 \
            -extprefix ${{ github.workspace }}/qt6-install-root \
            -opengl es2 \
            -nomake examples -nomake tests \
            -skip qtwebengine -skip qt3d -skip qtwayland \
            -- -GNinja

      - name: Build and Install
        run: |
          cd qt6-build
          ninja
          ninja install

      - name: Package Runtime
        run: |
          tar -czvf EndStation_Qt6_Runtime_ARM.tar.gz -C ${{ github.workspace }}/qt6-install-root .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Qt6-Everywhere-IMX6-Runtime
          path: EndStation_Qt6_Runtime_ARM.tar.gz
